version: 2
project_name: tofu-controller

release:
  prerelease: "true"
  extra_files:
    - glob: config/release/*.yaml

checksum:
  extra_files:
    - glob: config/release/*.yaml

builds:
  - id: tfctl
    main: ./cmd/tfctl
    binary: tfctl
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.BuildSHA={{.ShortCommit}} -X main.BuildVersion={{.Tag}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

archives:
  - id: tfctl
    builds:
      - tfctl
    name_template: "tfctl_{{ title .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source_code"

sboms:
  - id: source
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

# signs the checksum file
# all files (including the sboms) are included in the checksum
# https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true

brews:
  - name: tfctl
    ids:
    - tfctl
    repository:
      owner: flux-iac
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: flux-iac
      email: noreply@github.com
    directory: Formula
    homepage: https://flux-iac.github.io/tofu-controller
    install: |
      bin.install "tfctl"
