FROM alpine:3.22

LABEL org.opencontainers.image.source="https://github.com/flux-iac/tofu-controller"

RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache \
    ca-certificates tini git openssh-client gnupg \
    busybox

COPY bin/tofu-controller /usr/local/bin/

RUN addgroup --gid 65532 -S controller && adduser --uid 65532 -S controller -G controller

USER 65532:65532

ENV GNUPGHOME=/tmp

ENTRYPOINT [ "/sbin/tini", "--", "tofu-controller" ]
