name: verify

on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'MAINTAINERS'
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Verify
        run: make verify
